# Generated by Django 4.2 on 2024-11-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
