# Generated by Django 4.2 on 2024-11-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfo_age_userinfo_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='updated_at',
        ),
    ]
