# Generated by Django 4.2 on 2024-11-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
