# Generated by Django 5.1.3 on 2024-11-25 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_created_at_alter_profile_updated_at'),
        ('profile_app', '0006_alter_profile_created_at_alter_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
