# Generated by Django 5.1.3 on 2024-11-25 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_alter_profile_created_at_alter_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
